### ISSUE TITLE
Urls mark for incognito are also opening in normal mode

### ISSUE THREAD

**Issue by vipulbhj** [fxnoob/mark-incognito#10]
When you make a url as incognito, it will open in incognito but it will also open in users normal window which is a bug as it shouldn't be the case.

## Expected Behaviour:- 
Urls once marked will always open in incognito mode only

**Comment by HurricaneInteractive** [comment]
I'll investigate. I'll either create a PR or return with some findings if I can't get the code working.

**Comment by vipulbhj** [comment]
great, please go ahead

**Comment by HurricaneInteractive** [comment]
I think the issue lies here;
```js
await this.createIncognitoTab({
  url: url
});
return {
  redirectUrl: details.hasOwnProperty("initiator") ?
    details.initiator :
    ""
};
```

I think what is happening is; when the incognito tab/window is created that return method doesn't apply to the previous window anymore. So instead of doing a return, possibly might need to get the window the user clicked the link on and navigate back/prevent a load.

I can experiment with that tomorrow 👍
